BookiFy/Controllers/HomeController.cs
using BookiFy.Data.Interfaces;
using BookiFy.Models;
using BookiFy.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BookiFy.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly IItemRepository _itemRepository;
        private readonly ICategoryRepository _categoryRepository;
        public HomeController(IItemRepository itemRepository, ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
            _itemRepository = itemRepository;
            
        }
        public ViewResult Index()
        {
            var homeViewModel = new HomeViewModel
            {
                InStock = _itemRepository.Items
            };
            return View(homeViewModel);
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BookiFy/Controllers/ItemController.cs
using BookiFy.Data;
using BookiFy.Data.Interfaces;
using BookiFy.Data.Models;
using BookiFy.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookiFy.Controllers
{
    public class ItemController : Controller
    {
        private readonly AppDbContext _context;
       
        private readonly IItemRepository _itemRepository;
        private readonly ICategoryRepository _categoryRepository;
        public ItemController(IItemRepository itemRepository, ICategoryRepository categoryRepository,AppDbContext context)
        {
            _categoryRepository = categoryRepository;
            _itemRepository = itemRepository;
            _context = context;
        }
        public ViewResult List()
        {
            ViewBag.Name = "Items";
            ItemViewModel vm = new ItemViewModel();
            vm.Items = _itemRepository.Items;
            vm.CurrentCategory = "ItemCategory";
            return View(vm);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create([Bind("ItemId,ItemaName,ShortDescription,LongDescription,Price,Category,InStock")] Item item ,[Bind("CategoryId,CategoryName")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(item);
                
                _context.SaveChanges();
                return RedirectToAction("List");
            }

            return View(item);
        }
    }
}

BookiFy/Controllers/OrderController.cs
using BookiFy.Data.Interfaces;
using BookiFy.Data.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookiFy.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly ShoppingCart _shoppingCart;
        public OrderController(IOrderRepository orderRepository, ShoppingCart shoppingCart)
        {
            _orderRepository = orderRepository;
            _shoppingCart = shoppingCart;
        }
        public IActionResult CheckOut()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CheckOut(Order order)
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            if (_shoppingCart.ShoppingCartItems.Count == 0)
            {
                ModelState.AddModelError("", "Your card is empty, add some drinks first");
            }

            if (ModelState.IsValid)
            {
                _orderRepository.CreateOrder(order);
                _shoppingCart.ClearCart();
                return RedirectToAction("CheckOutComplete");
            }

            return View(order);
        }
        [HttpPost]
        public IActionResult CheckOutComplete()
        {
            ViewBag.CheckOutMessage = "Thanks For The Order";
            return View();
        }
    }
}

BookiFy/Controllers/ShoppingCartController.cs
using BookiFy.Data.Interfaces;
using BookiFy.Data.Models;
using BookiFy.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookiFy.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IItemRepository _itemRepository;
        private readonly ShoppingCart _shoppingCart;
        public ShoppingCartController(IItemRepository itemRepository, ShoppingCart shoppingCart)
        {
            _itemRepository = itemRepository;
            _shoppingCart = shoppingCart;
        }
        public IActionResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var sCVM = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = (double)_shoppingCart.GetShoppingCartTotal()

            };
            return View(sCVM);
        }
        public RedirectToActionResult AddToShoppingCart(int itemID)
        {
            var selectedItem = _itemRepository.Items.FirstOrDefault(p => p.ItemId == itemID);
            if (selectedItem != null)
            {
                _shoppingCart.AddToCart(selectedItem, 1);

            }
            return RedirectToAction("Index");
        }
        public RedirectToActionResult RemoveFromShoppingCart(int itemId)
        {
            var selectedItem = _itemRepository.Items.FirstOrDefault(p => p.ItemId == itemId);
            if (selectedItem != null)
            {
                _shoppingCart.RemoveFromCart(selectedItem, 1);

            }
            return RedirectToAction("Index");
        }
    }
}

BookiFy/Views/Home/Index.cshtml
@model HomeViewModel

<link rel="stylesheet" href="~/css/site.css" />
@*@await Html.PartialAsync("Carousel1")*@
<div class=" text-center ">
    <p class="text-center"><h1>BookiFy At Your Service</h1></p>
</div>
<br />
<div class="container , align-content-center">
    <img src="~/Images/SliderImage1.jpg" class="align-content-end" alt="">
    
    <a class="button1" 
       asp-controller="Item"
       asp-action="List"
      >Shop now</a>
</div>

    
@*<div class="row">
    @foreach (var item in Model.InStock)
    {
        @Html.Partial("ItemSummary", item)
    }
</div>*@

BookiFy/Views/Item/Create.cshtml
@model BookiFy.Data.Models.Item
@{
    ViewData["Title"] = "Create";
}
<h1>Create</h1>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ItemName" class="control-label"></label>
                <input asp-for="ItemName" class="form-control" />
                <span asp-validation-for="ItemName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortDescription" class="control-label"></label>
                <input asp-for="ShortDescription" class="form-control" />
                <span asp-validation-for="ShortDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LongDescription" class="control-label"></label>
                <input asp-for="LongDescription" class="form-control" />
                <span asp-validation-for="LongDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InStock" class="control-label"></label>
                <input asp-for="InStock" class="form-control" />
                <span asp-validation-for="InStock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <input asp-for="CategoryId" class="form-control" />
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

BookiFy/Views/Item/List.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    @using BookiFy.ViewModel;
    @model ItemViewModel
}
<div>
    <h1>
        All items are shown here<br />
        <a asp-action="Create">Post Your Item</a>
    </h1>
</div>
<div>
    
</div>
@{
    foreach (var item in Model.Items)
    {
        @Html.Partial("ItemSummary", item)
    }
}

BookiFy/Views/Order/CheckOut.cshtml
@{
    @using BookiFy.Data.Models;
    @model Order;
}


<div class="row orderForm ">


    <form asp-action="CheckOut" method="post" class="form-horizontal" role="form">
        <div class="form-group">
            <label asp-for="LastName" class="col-md-8 control-label"></label>
            <div class="col-md-8">
                <input asp-for="LastName" class="form-control" width="20" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="FirstName" class="col-md-8 control-label"></label>
            <div class="col-md-8">
                <input asp-for="FirstName" class="form-control" width="20" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
        </div>












        <div class="form-group">
            <label asp-for="PhoneNumber" class="col-md-8 control-label"></label>
            <div class="col-md-8">
                <input asp-for="PhoneNumber" class="form-control" size="10" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
        </div>


        <div class="form-group">
            <div class="btn-group col-md-offset-2 col-md-8">
                <input class="btn btn-success" type="submit" value="Complete order" />
                @*<input class="btn btn-default" type="submit" value="Return " />*@
            </div>
        </div>

    </form>
</div>

BookiFy/Views/Order/CheckOutComplete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>
    @ViewBag.CheckOutMessage
</h1>

BookiFy/Views/Shared/Carousel1.cshtml
<div class="row carousel-holder marginTop1">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
                <div class="carousel-inner">
                    <div class="item active">
                        <img class="slide-image" src="~/Images/carousel1.jpg" alt="">
                    </div>
                    <div class="item">
                        <img class="slide-image" src="~/Images/carousel2.jpg" alt="">
                    </div>
                    <div class="item">
                        <img class="slide-image" src="~/Images/carousel3.jpg" alt="">
                    </div>
                </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

BookiFy/Views/Shared/Components/ShoppingCartSummary/Default.cshtml
@{
    @using BookiFy.ViewModel;
    @model ShoppingCartViewModel
}
<link rel="stylesheet" href="~/css/site.css" />
@if (Model.ShoppingCart.ShoppingCartItems.Count > 0)
{
    <li>
        <a asp-controller="ShoppingCart"> 
            <span class=" glyphicon glyphicon-shopping-cart"><img src="~/Images/shopping-cart-icon-png-favpng-e5DiMUYLNYaTjdsibphFUCAxC.jpg" height="20px" width="20px"/> :</span>
            <span id="cart-status" >
                @Model.ShoppingCart.ShoppingCartItems.Count
            </span>
        </a>
    </li> 
}

BookiFy/Views/Shared/ItemSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    @using BookiFy.Data.Models
    @model Item
}
<div class=" col-sm-4 col-lg-4 col-md-4, float-sm-left">
    <div class="img-thumbnail">
        <img src="/Images/@Model.Image" alt="" height="200" width="200" />
        <div class="figure-caption">
            <h4>
                <a href="">@Model.ItemName</a>
            </h4>
            Price : @Model.Price
        </div>
        <div class="addToCart text-right">
            <p class="button">
                <a class="btn btn-success" id="cartButton"
                   asp-controller="ShoppingCart"
                   asp-action="AddToShoppingCart"
                   asp-route-itemId="@Model.ItemId">AddToCart</a>
            </p>
        </div>
    </div>

</div>

BookiFy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Capstone</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">BookiFy</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Item" asp-action="List">Items</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <partial name="_LoginPartial" />
                        <li>
                            @await Component.InvokeAsync("ShoppingCartSummary")
                            <a class="nav-link text-white" asp-area="" asp-controller="ShoppingCart" asp-action="Index">ShoppingCart</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BookiFy/Views/ShoppingCart/Index.cshtml
@{
    @using BookiFy.ViewModel;
    @model ShoppingCartViewModel
}
<div class="row checkoutForm">
    <h2>Your shopping cart</h2>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Selected amount</th>
                <th>Item</th>
                <th class="text-right">Price</th>
                <th class="text-right">Subtotal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.ShoppingCart.ShoppingCartItems)
            {
                <tr>
                    <td class="text-center">@line.Amount</td>
                    <td class="text-left">@line.Item.ItemName</td>
                    <td class="text-right">@line.Item.Price.ToString("c")</td>
                    <td class="text-right">
                        @((line.Amount * line.Item.Price).ToString("c"))
                    </td>
                    <td class="text-center"><a class="glyphicon glyphicon-remove text-danger remove" asp-controller="ShoppingCart" asp-action="RemoveFromShoppingCart" asp-route-itemId="@line.Item.ItemId">Remove</a></td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-right">Total:</td>
                <td class="text-right">
                    @Model.ShoppingCartTotal.ToString("c")
                </td>
            </tr>
        </tfoot>
    </table>

    <div class="text-right">
        <div class="btn-group ">
            <a class="btn btn-success" asp-controller="Order" asp-action="Checkout">Check out</a>
            <a class="btn-group">
                <a class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Add more items<span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a asp-controller="Item" asp-action="List" asp-route-category="Used">USED</a></li>
                    <li><a asp-controller="Item" asp-action="List" asp-route-category="New">NEW</a></li>
                </ul>
            </a>
        </div>
    </div>
</div>